export const ActionTypes = {
  SET_AGE_GROUP: "SET_AGE_GROUP",
  SET_SELECTED_DISTRICT_CODE: "SET_SELECTED_DISTRICT_CODE",
  REMOVE_SELECTED_DISTRICT_CODE: "REMOVE_SELECTED_DISTRICT_CODE",
  SET_SELECTED_STATE_CODE: "SET_SELECTED_STATE_CODE",
  SET_SELECTED_VACCINE: "SET_SELECTED_VACCINE",
  SET_FEE_TYPE: "SET_FEE_TYPE",
  SET_DOSE_NO: "SET_DOSE_NO",
};
